// ── ESPAÑOL ──────────────────────────────────────────────────────────────────
export const packItinerary_es = {
  "day-arrival-mkk":    { title: "Llegada a Marrakech",         desc: "Recogida en aeropuerto y traslado al riad. Cena de bienvenida con música andalusí." },
  "day-medina-mkk":     { title: "Medina y zocos",              desc: "Tour guiado por la medina, plaza Jemaa el-Fna y los zocos artesanales. Tarde libre." },
  "day-atlas-route":    { title: "Ruta al desierto por el Atlas",desc: "Salida hacia Merzouga atravesando el paso del Tizi n'Tichka y los valles del Atlas." },
  "day-sahara-night":   { title: "Sahara y noche en jaima",     desc: "Paseo en camello hasta las dunas de Erg Chebbi. Cena bereber y noche bajo las estrellas." },
  "day-return":         { title: "Regreso",                     desc: "Desayuno en el desierto, regreso a Marrakech y traslado al aeropuerto." },
  "day-travel-fez":     { title: "Camino a Fez",                desc: "Salida hacia Fez con parada en Beni Mellal y las gargantas del Todra." },
  "day-fez-medina":     { title: "Medina de Fez",               desc: "Tour por la medina más antigua del mundo: tenerías, madraza Bou Inania y barrios artesanos." },
  "day-meknes-volubilis":{ title: "Meknes y Volubilis",         desc: "Visita a la ciudad imperial de Meknes y las ruinas romanas de Volubilis." },
  "day-rabat":          { title: "Rabat, la capital",           desc: "Tour por la kasbah de los Udayas, la Torre Hassan y el mausoleo de Mohammed V." },
  "day-chefchaouen":    { title: "El pueblo azul",              desc: "Llegada a Chefchaouen, paseo por las calles azules y la medina bereber." },
  "day-souks-mkk":      { title: "Zocos y compras",             desc: "Mañana libre en los zocos de Marrakech. Tarde de relax en el riad." },
  "day-arrival-merzouga":{ title: "Llegada a Merzouga",         desc: "Traslado desde el aeropuerto al campamento de lujo en las dunas de Erg Chebbi." },
  "day-sahara-camel":   { title: "Dunas al amanecer",           desc: "Paseo en camello al amanecer, desayuno bereber y exploración libre del desierto." },
  "day-essaouira":      { title: "Essaouira, la ciudad del viento", desc: "Visita a la medina amurallada de Essaouira, sus galerías de arte y el puerto de pescadores." },
  "day-arrival-chef":   { title: "Llegada a Chefchaouen",       desc: "Traslado y check-in en el riad. Primer paseo por las calles azules al atardecer." },
  "day-chef-explore":   { title: "Chefchaouen a fondo",         desc: "Tour guiado por la medina, la kasbah y los miradores. Taller de cocina bereber." },
  "day-rif-mountains":  { title: "Las montañas del Rif",        desc: "Senderismo por los senderos del Rif con guía local. Almuerzo en pueblo bereber." },
};

// ── INGLÉS ───────────────────────────────────────────────────────────────────
export const packItinerary_en = {
  "day-arrival-mkk":    { title: "Arrival in Marrakech",        desc: "Airport pickup and transfer to riad. Welcome dinner with Andalusian music." },
  "day-medina-mkk":     { title: "Medina & souks",              desc: "Guided tour of the medina, Jemaa el-Fna square and artisan souks. Free afternoon." },
  "day-atlas-route":    { title: "Desert route via the Atlas",  desc: "Departure to Merzouga crossing the Tizi n'Tichka pass and the Atlas valleys." },
  "day-sahara-night":   { title: "Sahara & night in tent",      desc: "Camel ride to the Erg Chebbi dunes. Berber dinner and a night under the stars." },
  "day-return":         { title: "Return",                      desc: "Breakfast in the desert, return to Marrakech and airport transfer." },
  "day-travel-fez":     { title: "On the road to Fez",          desc: "Departure to Fez with a stop at the Todra Gorges." },
  "day-fez-medina":     { title: "Fez medina",                  desc: "Tour of the world's oldest medina: tanneries, Bou Inania madrasa and craft quarters." },
  "day-meknes-volubilis":{ title: "Meknes & Volubilis",         desc: "Visit to the imperial city of Meknes and the Roman ruins of Volubilis." },
  "day-rabat":          { title: "Rabat, the capital",          desc: "Tour of the Kasbah of the Udayas, Hassan Tower and Mohammed V Mausoleum." },
  "day-chefchaouen":    { title: "The blue village",            desc: "Arrival in Chefchaouen, stroll through the blue streets and Berber medina." },
  "day-souks-mkk":      { title: "Souks & shopping",            desc: "Free morning in Marrakech's souks. Afternoon relaxing at the riad." },
  "day-arrival-merzouga":{ title: "Arrival in Merzouga",        desc: "Transfer from the airport to the luxury camp in the Erg Chebbi dunes." },
  "day-sahara-camel":   { title: "Dunes at sunrise",            desc: "Camel ride at sunrise, Berber breakfast and free exploration of the desert." },
  "day-essaouira":      { title: "Essaouira, city of the wind", desc: "Visit to the walled medina of Essaouira, its art galleries and fishing harbour." },
  "day-arrival-chef":   { title: "Arrival in Chefchaouen",      desc: "Transfer and check-in at the riad. First stroll through the blue streets at sunset." },
  "day-chef-explore":   { title: "Chefchaouen in depth",        desc: "Guided tour of the medina, kasbah and viewpoints. Berber cooking workshop." },
  "day-rif-mountains":  { title: "The Rif Mountains",           desc: "Hiking through the Rif trails with a local guide. Lunch in a Berber village." },
};

// ── FRANCÉS ──────────────────────────────────────────────────────────────────
export const packItinerary_fr = {
  "day-arrival-mkk":    { title: "Arrivée à Marrakech",         desc: "Accueil à l'aéroport et transfert au riad. Dîner de bienvenue avec musique andalouse." },
  "day-medina-mkk":     { title: "Médina et souks",             desc: "Visite guidée de la médina, place Jemaa el-Fna et souks artisanaux. Après-midi libre." },
  "day-atlas-route":    { title: "Route du désert via l'Atlas", desc: "Départ vers Merzouga en traversant le col du Tizi n'Tichka et les vallées de l'Atlas." },
  "day-sahara-night":   { title: "Sahara et nuit sous tente",   desc: "Balade en chameau jusqu'aux dunes d'Erg Chebbi. Dîner berbère et nuit à la belle étoile." },
  "day-return":         { title: "Retour",                      desc: "Petit-déjeuner dans le désert, retour à Marrakech et transfert à l'aéroport." },
  "day-travel-fez":     { title: "En route vers Fès",           desc: "Départ vers Fès avec arrêt aux gorges du Todra." },
  "day-fez-medina":     { title: "Médina de Fès",               desc: "Tour de la plus ancienne médina du monde : tanneries, medersa Bou Inania et quartiers artisanaux." },
  "day-meknes-volubilis":{ title: "Meknès et Volubilis",        desc: "Visite de la ville impériale de Meknès et des ruines romaines de Volubilis." },
  "day-rabat":          { title: "Rabat, la capitale",          desc: "Tour de la Kasbah des Oudaïas, Tour Hassan et Mausolée Mohammed V." },
  "day-chefchaouen":    { title: "Le village bleu",             desc: "Arrivée à Chefchaouen, promenade dans les ruelles bleues et la médina berbère." },
  "day-souks-mkk":      { title: "Souks et shopping",           desc: "Matinée libre dans les souks de Marrakech. Après-midi de détente au riad." },
  "day-arrival-merzouga":{ title: "Arrivée à Merzouga",         desc: "Transfert depuis l'aéroport au camp de luxe dans les dunes d'Erg Chebbi." },
  "day-sahara-camel":   { title: "Dunes au lever du soleil",    desc: "Balade en chameau au lever du soleil, petit-déjeuner berbère et exploration libre." },
  "day-essaouira":      { title: "Essaouira, ville du vent",    desc: "Visite de la médina fortifiée d'Essaouira, ses galeries d'art et son port de pêche." },
  "day-arrival-chef":   { title: "Arrivée à Chefchaouen",       desc: "Transfert et check-in au riad. Première promenade dans les ruelles bleues au coucher du soleil." },
  "day-chef-explore":   { title: "Chefchaouen en profondeur",   desc: "Visite guidée de la médina, kasbah et belvédères. Atelier de cuisine berbère." },
  "day-rif-mountains":  { title: "Les montagnes du Rif",        desc: "Randonnée dans les sentiers du Rif avec guide local. Déjeuner dans un village berbère." },
};

// ── ALEMÁN ───────────────────────────────────────────────────────────────────
export const packItinerary_de = {
  "day-arrival-mkk":    { title: "Ankunft in Marrakesch",       desc: "Abholung am Flughafen und Transfer zum Riad. Willkommensdinner mit andalusischer Musik." },
  "day-medina-mkk":     { title: "Medina und Souks",            desc: "Geführte Tour durch die Medina, den Jemaa el-Fna-Platz und die Handwerkssouks." },
  "day-atlas-route":    { title: "Wüstenroute über den Atlas",  desc: "Abfahrt nach Merzouga über den Tizi n'Tichka-Pass und die Atlastäler." },
  "day-sahara-night":   { title: "Sahara und Nacht im Zelt",    desc: "Kamelritt zu den Erg-Chebbi-Dünen. Berber-Dinner und Nacht unter dem Sternenhimmel." },
  "day-return":         { title: "Rückreise",                   desc: "Frühstück in der Wüste, Rückfahrt nach Marrakesch und Flughafentransfer." },
  "day-travel-fez":     { title: "Unterwegs nach Fès",          desc: "Abfahrt nach Fès mit Halt an den Todra-Schluchten." },
  "day-fez-medina":     { title: "Medina von Fès",              desc: "Tour durch die älteste Medina der Welt: Gerbereien, Bou-Inania-Madrasa und Handwerksviertel." },
  "day-meknes-volubilis":{ title: "Meknès und Volubilis",       desc: "Besuch der Kaiserstadt Meknès und der römischen Ruinen von Volubilis." },
  "day-rabat":          { title: "Rabat, die Hauptstadt",       desc: "Tour durch die Kasbah der Udayas, den Hassan-Turm und das Mausoleum Mohammed V." },
  "day-chefchaouen":    { title: "Das blaue Dorf",              desc: "Ankunft in Chefchaouen, Spaziergang durch die blauen Gassen und die Berber-Medina." },
  "day-souks-mkk":      { title: "Souks und Einkaufen",         desc: "Freier Vormittag in den Souks von Marrakesch. Entspannter Nachmittag im Riad." },
  "day-arrival-merzouga":{ title: "Ankunft in Merzouga",        desc: "Transfer vom Flughafen zum Luxuscamp in den Erg-Chebbi-Dünen." },
  "day-sahara-camel":   { title: "Dünen bei Sonnenaufgang",     desc: "Kamelritt bei Sonnenaufgang, Berber-Frühstück und freie Erkundung der Wüste." },
  "day-essaouira":      { title: "Essaouira, Stadt des Windes", desc: "Besuch der befestigten Medina von Essaouira, ihrer Kunstgalerien und des Fischerhafens." },
  "day-arrival-chef":   { title: "Ankunft in Chefchaouen",      desc: "Transfer und Check-in im Riad. Erster Spaziergang durch die blauen Gassen bei Sonnenuntergang." },
  "day-chef-explore":   { title: "Chefchaouen entdecken",       desc: "Geführte Tour durch Medina, Kasbah und Aussichtspunkte. Berber-Kochworkshop." },
  "day-rif-mountains":  { title: "Das Rifgebirge",              desc: "Wanderung auf Rifpfaden mit lokalem Führer. Mittagessen in einem Berberdorf." },
};

// ── ITALIANO ─────────────────────────────────────────────────────────────────
export const packItinerary_it = {
  "day-arrival-mkk":    { title: "Arrivo a Marrakech",          desc: "Accoglienza in aeroporto e trasferimento al riad. Cena di benvenuto con musica andalusa." },
  "day-medina-mkk":     { title: "Medina e souk",               desc: "Tour guidato della medina, piazza Jemaa el-Fna e souk artigianali. Pomeriggio libero." },
  "day-atlas-route":    { title: "Rotta del deserto via l'Atlante", desc: "Partenza per Merzouga attraversando il passo Tizi n'Tichka e le valli dell'Atlante." },
  "day-sahara-night":   { title: "Sahara e notte in tenda",     desc: "Escursione in cammello alle dune di Erg Chebbi. Cena berbera e notte sotto le stelle." },
  "day-return":         { title: "Ritorno",                     desc: "Colazione nel deserto, rientro a Marrakech e trasferimento all'aeroporto." },
  "day-travel-fez":     { title: "In viaggio verso Fès",        desc: "Partenza per Fès con sosta alle gole del Todra." },
  "day-fez-medina":     { title: "Medina di Fès",               desc: "Tour della medina più antica del mondo: concerie, madrasa Bou Inania e quartieri artigiani." },
  "day-meknes-volubilis":{ title: "Meknès e Volubilis",         desc: "Visita alla città imperiale di Meknès e alle rovine romane di Volubilis." },
  "day-rabat":          { title: "Rabat, la capitale",          desc: "Tour della Kasbah degli Udaya, Torre Hassan e Mausoleo di Mohammed V." },
  "day-chefchaouen":    { title: "Il villaggio blu",            desc: "Arrivo a Chefchaouen, passeggiata tra le strade blu e la medina berbera." },
  "day-souks-mkk":      { title: "Souk e shopping",             desc: "Mattinata libera nei souk di Marrakech. Pomeriggio di relax al riad." },
  "day-arrival-merzouga":{ title: "Arrivo a Merzouga",          desc: "Trasferimento dall'aeroporto al campo di lusso nelle dune di Erg Chebbi." },
  "day-sahara-camel":   { title: "Dune all'alba",               desc: "Escursione in cammello all'alba, colazione berbera ed esplorazione libera del deserto." },
  "day-essaouira":      { title: "Essaouira, città del vento",  desc: "Visita alla medina murata di Essaouira, le sue gallerie d'arte e il porto dei pescatori." },
  "day-arrival-chef":   { title: "Arrivo a Chefchaouen",        desc: "Trasferimento e check-in al riad. Prima passeggiata tra le strade blu al tramonto." },
  "day-chef-explore":   { title: "Chefchaouen in profondità",   desc: "Tour guidato della medina, kasbah e belvederi. Workshop di cucina berbera." },
  "day-rif-mountains":  { title: "Le montagne del Rif",         desc: "Trekking sui sentieri del Rif con guida locale. Pranzo in un villaggio berbero." },
};
